services:
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    hostname: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_WEBUI_PORT=8081
      - HADOOP_CONF_DIR=/opt/hadoop/conf
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    ports:
      - "8081:8081"   # UI worker
    depends_on:
      - spark-master
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./spark-data:/opt/spark-data
      - ./hadoop-conf:/opt/hadoop/conf:ro
    networks:
      - hadoop_network
    restart: unless-stopped

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    hostname: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - HADOOP_CONF_DIR=/opt/hadoop/conf
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    ports:
      - "8080:8080"   # UI master
      - "7077:7077"   # Spark master
    volumes:
      - ./spark-apps:/opt/spark-apps
      - ./spark-data:/opt/spark-data
      - ./hadoop-conf:/opt/hadoop/conf:ro
    networks:
      - hadoop_network
    restart: unless-stopped

  jupyter:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: jupyter
    hostname: jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_MASTER_URL=spark://spark-master:7077
      - HADOOP_CONF_DIR=/opt/hadoop/conf
      - PYSPARK_SUBMIT_ARGS=--master spark://spark-master:7077 pyspark-shell
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./hadoop-conf:/opt/hadoop/conf:ro
    depends_on:
      - spark-master
      - spark-worker
      - namenode
      - datanode
    networks:
      - hadoop_network
    restart: unless-stopped

  mongodb:
    image: mongo:${MONGO_VERSION}
    container_name: mongodb
    command: ["mongod", "--bind_ip_all"]
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodata:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d:ro
    networks:
      - tpnet

    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping').ok\" | grep 1 >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 20s
  cassandra:
    image: cassandra:4.1
    container_name: tp_cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TPCluster
    volumes:
      - cassandra_data:/var/lib/cassandra

  neo4j:
    image: neo4j:5
    container_name: tp_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data